name: ChunkWorldEditorPlus
main: ChunkWorldEditorPlus\main
version: 1.0Î²
api: 3.0.0
load: POSTWORLD
commands:
 cset:
  description: 
  usage: "/cset"
 cmset:
  description: 
  usage: "/cmset"
 cundo:
  description: 
  usage: "/cundo"
 csphere:
  description: 
  usage: "/csphere"
 cmsphere:
  description: 
  usage: "/cmsphere"
 csp:
  description: 
  usage: "/csp"
 cmsp:
  description: 
  usage: "/cmsp"
 cbox:
  description: 
  usage: "/cbox"
 cmbox:
  description: 
  usage: "/cmbox"
 cfast:
  description: 
  usage: "/cfast"
 csetpp:
  description:
  usage: "/csetpp"
 crp:
   description:
   usage: "/crp"
